template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Models/ErrorViewModel.cs
namespace AspnetCoreMvcFull.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class AuthController : Controller
{
  public IActionResult ForgotPasswordBasic() => View();
  public IActionResult LoginBasic() => View();
  public IActionResult RegisterBasic() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/CardsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class CardsController : Controller
{
  public IActionResult Basic() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/DashboardsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class DashboardsController : Controller
{
  public IActionResult Index() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/ExtendedUiController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class ExtendedUiController : Controller
{
  public IActionResult PerfectScrollbar() => View();
  public IActionResult TextDivider() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/FormLayoutsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class FormLayoutsController : Controller
{
public IActionResult Horizontal() => View();
public IActionResult Vertical() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/FormsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class FormsController : Controller
{
  public IActionResult BasicInputs() => View();
  public IActionResult InputGroups() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/IconsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class IconsController : Controller
{
  public IActionResult Boxicons() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/LayoutExamplesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class LayoutExamplesController : Controller
{
  public IActionResult Blank() => View();
  public IActionResult Container() => View();
  public IActionResult Fluid() => View();
  public IActionResult HorizontalMenu() => View();
  public IActionResult WithoutMenu() => View();
  public IActionResult WithoutNavbar() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/PagesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class PagesController : Controller
{
  public IActionResult AccountSettings() => View();
  public IActionResult AccountSettingsConnections() => View();
  public IActionResult AccountSettingsNotifications() => View();
  public IActionResult MiscError() => View();
  public IActionResult MiscUnderMaintenance() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/TablesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class TablesController : Controller
{
  public IActionResult Basic() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Controllers/UiController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class UiController : Controller
{
  public IActionResult Accordion() => View();
  public IActionResult Alerts() => View();
  public IActionResult Badges() => View();
  public IActionResult Buttons() => View();
  public IActionResult Carousel() => View();
  public IActionResult Collapse() => View();
  public IActionResult Dropdowns() => View();
  public IActionResult Footer() => View();
  public IActionResult ListGroups() => View();
  public IActionResult Modals() => View();
  public IActionResult Navbar() => View();
  public IActionResult Offcanvas() => View();
  public IActionResult PaginationBreadcrumbs() => View();
  public IActionResult Progress() => View();
  public IActionResult Spinners() => View();
  public IActionResult TabsPills() => View();
  public IActionResult Toasts() => View();
  public IActionResult TooltipsPopovers() => View();
  public IActionResult Typography() => View();
}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/FormLayouts/Horizontal.cshtml
@{
  ViewData["Title"] = "Horizontal Form - Form Layouts";
}

@* ************** Content ************** *@
<!-- Basic Layout & Basic with Icons -->
<div class="row mb-6 gy-6">
  <!-- Basic Layout -->
  <div class="col-xxl">
    <div class="card">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Basic Layout</h5>
        <small class="text-body-secondary float-end">Default label</small>
      </div>
      <div class="card-body">
        <form>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-default-name">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="basic-default-name" placeholder="John Doe" />
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-default-company">Company</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="basic-default-company" placeholder="ACME Inc." />
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-default-email">Email</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <input type="text" id="basic-default-email" class="form-control" placeholder="john.doe" aria-label="john.doe" aria-describedby="basic-default-email2" />
                <span class="input-group-text" id="basic-default-email2">&#64;example.com</span>
              </div>
              <div class="form-text">You can use letters, numbers & periods</div>
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-default-phone">Phone No</label>
            <div class="col-sm-10">
              <input type="text" id="basic-default-phone" class="form-control phone-mask" placeholder="658 799 8941" aria-label="658 799 8941" aria-describedby="basic-default-phone" />
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-default-message">Message</label>
            <div class="col-sm-10">
              <textarea id="basic-default-message" class="form-control" placeholder="Hi, Do you have a moment to talk Joe?" aria-label="Hi, Do you have a moment to talk Joe?" aria-describedby="basic-icon-default-message2"></textarea>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- Basic with Icons -->
  <div class="col-xxl">
    <div class="card">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Basic with Icons</h5>
        <small class="text-body-secondary float-end">Merged input group</small>
      </div>
      <div class="card-body">
        <form>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Name</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <span id="basic-icon-default-fullname2" class="input-group-text"><i class="icon-base bx bx-user"></i></span>
                <input type="text" class="form-control" id="basic-icon-default-fullname" placeholder="John Doe" aria-label="John Doe" aria-describedby="basic-icon-default-fullname2" />
              </div>
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-icon-default-company">Company</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <span id="basic-icon-default-company2" class="input-group-text"><i class="icon-base bx bx-buildings"></i></span>
                <input type="text" id="basic-icon-default-company" class="form-control" placeholder="ACME Inc." aria-label="ACME Inc." aria-describedby="basic-icon-default-company2" />
              </div>
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-icon-default-email">Email</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <span class="input-group-text"><i class="icon-base bx bx-envelope"></i></span>
                <input type="text" id="basic-icon-default-email" class="form-control" placeholder="john.doe" aria-label="john.doe" aria-describedby="basic-icon-default-email2" />
                <span id="basic-icon-default-email2" class="input-group-text">&#64;example.com</span>
              </div>
              <div class="form-text">You can use letters, numbers & periods</div>
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-icon-default-phone">Phone No</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <span id="basic-icon-default-phone2" class="input-group-text"><i class="icon-base bx bx-phone"></i></span>
                <input type="text" id="basic-icon-default-phone" class="form-control phone-mask" placeholder="658 799 8941" aria-label="658 799 8941" aria-describedby="basic-icon-default-phone2" />
              </div>
            </div>
          </div>
          <div class="row mb-6">
            <label class="col-sm-2 col-form-label" for="basic-icon-default-message">Message</label>
            <div class="col-sm-10">
              <div class="input-group input-group-merge">
                <span id="basic-icon-default-message2" class="input-group-text"><i class="icon-base bx bx-comment"></i></span>
                <textarea id="basic-icon-default-message" class="form-control" placeholder="Hi, Do you have a moment to talk Joe?" aria-label="Hi, Do you have a moment to talk Joe?" aria-describedby="basic-icon-default-message2"></textarea>
              </div>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/FormLayouts/Vertical.cshtml
@{
  ViewData["Title"] = "Vertical Form - Form Layouts";
}

@* ************** Content ************** *@
<!-- Basic Layout -->
<div class="row mb-6 gy-6">
  <div class="col-xl">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Basic Layout</h5>
        <small class="text-body float-end">Default label</small>
      </div>
      <div class="card-body">
        <form>
          <div class="mb-6">
            <label class="form-label" for="basic-default-fullname">Full Name</label>
            <input type="text" class="form-control" id="basic-default-fullname" placeholder="John Doe" />
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-default-company">Company</label>
            <input type="text" class="form-control" id="basic-default-company" placeholder="ACME Inc." />
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-default-email">Email</label>
            <div class="input-group input-group-merge">
              <input type="text" id="basic-default-email" class="form-control" placeholder="john.doe" aria-label="john.doe" aria-describedby="basic-default-email2" />
              <span class="input-group-text" id="basic-default-email2">&#64;example.com</span>
            </div>
            <div class="form-text">You can use letters, numbers & periods</div>
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-default-phone">Phone No</label>
            <input type="text" id="basic-default-phone" class="form-control phone-mask" placeholder="658 799 8941" />
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-default-message">Message</label>
            <textarea id="basic-default-message" class="form-control" placeholder="Hi, Do you have a moment to talk Joe?"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Send</button>
        </form>
      </div>
    </div>
  </div>
  <div class="col-xl">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Basic with Icons</h5>
        <small class="text-body float-end">Merged input group</small>
      </div>
      <div class="card-body">
        <form>
          <div class="mb-6">
            <label class="form-label" for="basic-icon-default-fullname">Full Name</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-fullname2" class="input-group-text"><i class="icon-base bx bx-user"></i></span>
              <input type="text" class="form-control" id="basic-icon-default-fullname" placeholder="John Doe" aria-label="John Doe" aria-describedby="basic-icon-default-fullname2" />
            </div>
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-icon-default-company">Company</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-company2" class="input-group-text"><i class="icon-base bx bx-buildings"></i></span>
              <input type="text" id="basic-icon-default-company" class="form-control" placeholder="ACME Inc." aria-label="ACME Inc." aria-describedby="basic-icon-default-company2" />
            </div>
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-icon-default-email">Email</label>
            <div class="input-group input-group-merge">
              <span class="input-group-text"><i class="icon-base bx bx-envelope"></i></span>
              <input type="text" id="basic-icon-default-email" class="form-control" placeholder="john.doe" aria-label="john.doe" aria-describedby="basic-icon-default-email2" />
              <span id="basic-icon-default-email2" class="input-group-text">&#64;example.com</span>
            </div>
            <div class="form-text">You can use letters, numbers & periods</div>
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-icon-default-phone">Phone No</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-phone2" class="input-group-text"><i class="icon-base bx bx-phone"></i></span>
              <input type="text" id="basic-icon-default-phone" class="form-control phone-mask" placeholder="658 799 8941" aria-label="658 799 8941" aria-describedby="basic-icon-default-phone2" />
            </div>
          </div>
          <div class="mb-6">
            <label class="form-label" for="basic-icon-default-message">Message</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-message2" class="input-group-text"><i class="icon-base bx bx-comment"></i></span>
              <textarea id="basic-icon-default-message" class="form-control" placeholder="Hi, Do you have a moment to talk Joe?" aria-label="Hi, Do you have a moment to talk Joe?" aria-describedby="basic-icon-default-message2"></textarea>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Send</button>
        </form>
      </div>
    </div>
  </div>
</div>

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/Shared/Sections/Navbar/_Navbar.cshtml
@{
  TempData.Keep();
  @* ViewData["navbarDetached"] = (ViewData["navbarDetached"] ?? "navbar-detached"); *@
  ViewData["navbarDetached"] = (ViewData["navbarDetached"] ??= null);
  ViewData["containerNav"] = (ViewData["containerNav"] ??= "container-fluid");
}
@if (@ViewData["navbarDetached"] != null)
{
  <nav
  class='layout-navbar @((@ViewData["navbarDetached"] != null) ? @ViewData["navbarDetached"] : "") @((@ViewData["navbarDetached"] != null) ? @ViewData["containerNav"] : "") navbar navbar-expand-xl align-items-center bg-navbar-theme'
  id="layout-navbar">
  @await Html.PartialAsync("Sections/Navbar/_NavbarPartial")
  </nav>
}
else
{
  <nav
  class='layout-navbar @((@ViewData["navbarDetached"] != null) ? @ViewData["navbarDetached"] : "") @((@ViewData["navbarDetached"] != null) ? @ViewData["containerNav"] : "") navbar navbar-expand-xl align-items-center'
  id="layout-navbar">
  <div class='@((@ViewData["navbarDetached"] == null) ? @ViewData["containerNav"] : "")'>
    @await Html.PartialAsync("Sections/Navbar/_NavbarPartial")
    </div>
  </nav>

}

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/Shared/Sections/Navbar/_NavbarPartial.cshtml
@* ! Brand demo (display only for navbar-full and hide on below xl) *@
@if (ViewData["navbarFull"] != null)
{
<div class="navbar-brand app-brand demo d-none d-xl-flex py-0 me-4">
  <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link gap-2">
      <span class="app-brand-logo demo">
        @await Html.PartialAsync("../_Partials/_Macros")
      </span>
      <span class="app-brand-text demo menu-text fw-bold text-heading">@TempData.Peek("appName")</span>
    </a>

    @* ! Display menu close icon only for horizontal-menu with navbar-full *@
    @if (Convert.ToBoolean(@TempData.Peek("menuHorizontal")).ToString() == "True")
    {
      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-xl-none">
        <i class="icon-base bx bx-chevron-left d-flex align-items-center justify-content-center"></i>
      </a>
    }
  </div>
}

@* ! Not required for layout-without-menu *@
@if (ViewData["navbarHideToggle"] == null)
{
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-4 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-6" href="javascript:void(0)">
      <i class="icon-base bx bx-menu bx-md"></i>
    </a>
  </div>
}


<div class="navbar-nav-right d-flex align-items-center justify-content-end" id="navbar-collapse">

  <!-- Search -->
    <div class="navbar-nav align-items-center me-auto">
      <div class="nav-item d-flex align-items-center">
        <span class="w-px-22 h-px-22"><i class="icon-base bx bx-search icon-md"></i></span>
        <input type="text" class="form-control border-0 shadow-none ps-1 ps-sm-2 d-md-block d-none" placeholder="Search..." aria-label="Search..." />
      </div>
    </div>
  <!-- /Search -->



  <ul class="navbar-nav flex-row align-items-center ms-md-auto">
    <!-- Place this tag where you want the button to render. -->
    <li class="nav-item lh-1 me-4">
      <a class="github-button" href="https://github.com/themeselection/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star themeselection/sneat-html-admin-template-free on GitHub">Star</a>
    </li>

    <!-- User -->
    <li class="nav-item navbar-dropdown dropdown-user dropdown">
      <a class="nav-link dropdown-toggle hide-arrow p-0" href="javascript:void(0);" data-bs-toggle="dropdown">
        <div class="avatar avatar-online">
          <img src="~/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
        </div>
      </a>
      <ul class="dropdown-menu dropdown-menu-end">
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <div class="d-flex">
              <div class="flex-shrink-0 me-3">
                <div class="avatar avatar-online">
                  <img src="~/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                </div>
              </div>
              <div class="flex-grow-1">
                <h6 class="mb-0">John Doe</h6>
                <small class="text-body-secondary">Admin</small>
              </div>
            </div>
          </a>
        </li>
        <li>
          <div class="dropdown-divider my-1"></div>
        </li>
        <li>
          <a class="dropdown-item" asp-controller="Pages" asp-action="ProfileUser"> <i class="icon-base bx bx-user icon-md me-3"></i><span>My Profile</span> </a>
        </li>
        <li>
          <a class="dropdown-item" asp-controller="Pages" asp-action="AccountSettings"> <i class="icon-base bx bx-cog icon-md me-3"></i><span>Settings</span> </a>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <span class="d-flex align-items-center align-middle">
              <i class="flex-shrink-0 icon-base bx bx-credit-card icon-md me-3"></i><span class="flex-grow-1 align-middle">Billing Plan</span>
              <span class="flex-shrink-0 badge rounded-pill bg-danger">4</span>
            </span>
          </a>
        </li>
        <li>
          <div class="dropdown-divider my-1"></div>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);"> <i class="icon-base bx bx-power-off icon-md me-3"></i><span>Log Out</span> </a>
        </li>
      </ul>
    </li>
    <!--/ User -->

  </ul>
</div>

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/Shared/_BlankLayout.cshtml
@{
  Layout = "_CommonMasterLayout";
}

@section VendorStyles { @RenderSection("VendorStyles", required: false) }

@section PageStyles { @RenderSection("PageStyles", required: false) }

@RenderBody()

@section VendorScripts { @RenderSection("VendorScripts", required: false) }

@section PageScripts { @RenderSection("PageScripts", required: false) }

template/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free-v3.0.0/Views/Shared/_CommonMasterLayout.cshtml
@{
  @* Compact/Fluid class *@
  ViewData["contentType"] = ViewData["container"] is string container && container == "container-xxl" ? "layout-compact layout-menu-fixed" : "";
}

@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en" class="@(ViewData["navbarType"] is string navbarType ? navbarType : "")
@(ViewData["menuFixed"] is string menuFixed ? menuFixed : "")
@(ViewData["menuCollapsed"] is string menuCollapsed ? menuCollapsed : "")
@(ViewData["contentType"] is string contentType ? contentType : "")
@(ViewData["footerFixed"] is string footerFixed ? footerFixed : "")
@(ViewData["customizerHidden"] is string customizerHidden ? customizerHidden : "")" dir="ltr" data-skin="default" data-bs-theme="light" data-assets-path='@((httpContextAccessor.HttpContext?.Request.PathBase ?? "") + "/")' data-template='@(("vertical-menu-template-free"))'>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <meta name="robots" content="noindex, nofollow" />

  @{
    string title = ViewData["title"] as string ?? "";
    string appName = TempData.Peek("appName") as string ?? "";
    string productPage = TempData.Peek("productPage") as string ?? "";
    }
  <title>@title | @appName - Asp.Net Core MVC Free Admin Template</title>
  <meta name="description" content="" />

  <!-- Canonical SEO -->
  <link rel="canonical" href='@productPage'>
  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="~/img/favicon/favicon.ico" />

  <!-- Core Styles -->
  @await Html.PartialAsync("Sections/_Styles")

  <!-- Vendor Styles -->
  @RenderSection("VendorStyles", required: false)

  <!-- Page Styles -->
  @RenderSection("PageStyles", required: false)

  <!-- Include Scripts for customizer, helper, analytics, config -->
  @await Html.PartialAsync("Sections/_ScriptsIncludes")
</head>

<body>
  <!-- Layout Content -->
  @RenderBody()
  <!--/ Layout Content -->

  <!-- Core Scripts -->
  @await Html.PartialAsync("Sections/_Scripts")

  <!-- Vendor Scripts -->
  @RenderSection("VendorScripts", required: false)


  

  <!-- Main JS-->
  <script src='~/js/main.js'></script>

  <!-- Page Scripts-->
  @RenderSection("PageScripts", required: false)

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>

</body>

</html>